### ISSUE TITLE
 Other means of payment to support you or another way to buy the book

### ISSUE THREAD

**Issue by scwall** [adamchainz/django-htmx#163]
### Description

Hello,

I don't have a credit card and I can't pay for your book, which looks really good. I wanted to buy it to support the project, but would it be possible to pay you by another way? Paypal/Mollie/crypto/.... and if possible receive the book 😄 

Thank you in advance

**Comment by adamchainz** [comment]
Hi Pascal

Gumroad supports Paypal but I had to disable it due to the extra accounting overhead and fees that Paypal imposes on me.

I can only support Gumroad's payments at this time. If you can't make that work right now, don't worry. Perhaps one day you will be able to place an order via an employer or similar!

Thanks,

Adam
